import { ToolData } from './tool-types';

export const tools: ToolData[] = [
  {
    slug: "bolt-new",
    title: "Bolt.new",
    description: "The AI-powered web development platform that generates full-stack code instantly in your browser.",
    category: "Coding",
    pricing: "Freemium",
    websiteUrl: "https://bolt.new",
    color: "text-blue-500",
    bgGradient: "from-blue-500/20 to-blue-600/20",
    features: ["Instant Preview", "Full-stack Generation", "Browser IDE", "WebContainer Integration"],
    pros: ["Zero setup time", "Great for next.js projects", "Live preview"],
    cons: ["Only for web frameworks", "Cloud dependency"],
    isFeatured: true,
  },
  {
    slug: "windsurf-ide",
    title: "Windsurf",
    description: "Codeium's agentic IDE that predicts your next steps and works as an intelligent pair programmer.",
    category: "Coding",
    pricing: "Paid",
    websiteUrl: "https://codeium.com/windsurf",
    color: "text-emerald-500",
    bgGradient: "from-emerald-500/20 to-emerald-600/20",
    features: ["Flow State", "Deep Codebase Context", "Agentic Chat", "Refactoring Engine"],
    pros: ["Very fast AI responses", "Deep context understanding", "Built-in intelligent chat"],
    cons: ["Paid only", "Requires learning new workflows"],
    isFeatured: true,
  },
  {
    slug: "openai-sora",
    title: "Sora",
    description: "OpenAI's groundbreaking text-to-video AI model that creates hyper-realistic and imaginative scenes.",
    category: "Design",
    pricing: "Enterprise",
    websiteUrl: "https://openai.com/sora",
    color: "text-indigo-500",
    bgGradient: "from-indigo-500/20 to-indigo-600/20",
    features: ["Text-to-Video", "Photorealism", "Physical World Simulation", "High Quality Generaton"],
    pros: ["Unmatched quality", "Understands physical dynamics", "Longer video generations"],
    cons: ["Not widely available yet", "High cost API"],
    isFeatured: true,
  },
  {
    slug: "devin-ai",
    title: "Devin",
    description: "The world's first fully autonomous AI software engineer capable of taking Jira tickets to production.",
    category: "Assistance",
    pricing: "Paid",
    websiteUrl: "https://cognition-labs.ai",
    color: "text-purple-500",
    bgGradient: "from-purple-500/20 to-purple-600/20",
    features: ["Autonomous Coding", "Self Debugging", "Integration Planning", "Continuous Deployment"],
    pros: ["Can handle complex tickets alone", "Learns from its mistakes", "Works 24/7"],
    cons: ["Still in early access", "Can be unpredictable on large monolithic legacy codebases"],
    isFeatured: true,
  },
  {
    slug: "galileo-ai",
    title: "Galileo AI",
    description: "Generative UI design tool that turns text prompts into editable Figma designs instantly.",
    category: "Design",
    pricing: "Freemium",
    websiteUrl: "https://usegalileo.ai",
    color: "text-pink-500",
    bgGradient: "from-pink-500/20 to-pink-600/20",
    features: ["Text to Figma", "Design System Integration", "Component Auto-Generation", "UI Variations"],
    pros: ["Speeds up initial wireframing", "Outputs real Figma layers", "Modern design defaults"],
    cons: ["Can produce generic designs", "Requires manual polish"],
    isFeatured: true,
  },
  {
    slug: "cursor",
    title: "Cursor",
    description: "The AI-first code editor built for pair-programming with frontier models like Claude and GPT.",
    category: "Coding",
    pricing: "Freemium",
    websiteUrl: "https://cursor.com",
    color: "text-zinc-300",
    bgGradient: "from-zinc-500/20 to-zinc-700/20",
    features: ["Composer Agent", "Codebase Q&A", "Multi-file edits", "Tab autocomplete"],
    pros: ["Best-in-class agentic coding", "Fast cursor predictions", "Native VS Code feel"],
    cons: ["Pro plan needed for heavy use", "Index can be slow on huge repos"],
    isFeatured: true,
  },
  {
    slug: "github-copilot",
    title: "GitHub Copilot",
    description: "GitHub's AI pair programmer with inline suggestions, chat, and agents inside your IDE.",
    category: "Coding",
    pricing: "Paid",
    websiteUrl: "https://github.com/features/copilot",
    color: "text-violet-400",
    bgGradient: "from-violet-500/20 to-violet-700/20",
    features: ["Inline completions", "Copilot Chat", "Workspace context", "PR summaries"],
    pros: ["Tight GitHub integration", "Works in most IDEs", "Strong enterprise story"],
    cons: ["Less agentic than Cursor", "Suggestions can be generic"],
    isFeatured: true,
  },
  {
    slug: "claude",
    title: "Claude",
    description: "Anthropic's frontier AI assistant, powered by Claude Opus 4.8 — best-in-class for long context, writing, and complex reasoning.",
    category: "Assistance",
    pricing: "Freemium",
    websiteUrl: "https://claude.ai",
    color: "text-orange-400",
    bgGradient: "from-orange-500/20 to-amber-500/20",
    features: ["Claude Opus 4.8", "Artifacts", "Projects", "Computer use"],
    pros: ["Excellent at writing and code review", "Strong safety and steerability", "Long context handling"],
    cons: ["Image generation not native", "Slower on simple queries"],
    isFeatured: true,
  },
  {
    slug: "chatgpt",
    title: "ChatGPT",
    description: "OpenAI's flagship assistant, powered by GPT-5.5 — voice, vision, and a sprawling ecosystem of custom GPTs.",
    category: "Assistance",
    pricing: "Freemium",
    websiteUrl: "https://chat.openai.com",
    color: "text-emerald-400",
    bgGradient: "from-emerald-500/20 to-teal-500/20",
    features: ["GPT-5.5", "Voice mode", "Custom GPTs", "Data analysis"],
    pros: ["Most polished consumer UX", "Huge plugin ecosystem", "Strong multimodal"],
    cons: ["Rate limits on Plus", "Memory can drift on long sessions"],
    isFeatured: true,
  },
  {
    slug: "v0-by-vercel",
    title: "v0 by Vercel",
    description: "Generative UI tool from Vercel that ships production-ready React + Tailwind components from a prompt.",
    category: "Coding",
    pricing: "Freemium",
    websiteUrl: "https://v0.dev",
    color: "text-white",
    bgGradient: "from-zinc-700/20 to-zinc-900/20",
    features: ["Prompt to React", "shadcn/ui output", "Iterative refinement", "One-click deploy"],
    pros: ["Output is real, clean code", "Direct deploy to Vercel", "Great for landing pages"],
    cons: ["Stuck in React + Tailwind world", "Complex flows still need a human"],
    isFeatured: true,
  },
  {
    slug: "replit",
    title: "Replit",
    description: "Browser IDE with an AI agent that builds, runs, and deploys full apps from natural language.",
    category: "Coding",
    pricing: "Freemium",
    websiteUrl: "https://replit.com",
    color: "text-orange-500",
    bgGradient: "from-orange-500/20 to-red-500/20",
    features: ["Replit Agent", "Live multiplayer", "One-click hosting", "Mobile coding"],
    pros: ["Zero setup", "Great for prototyping", "Built-in deploys"],
    cons: ["Performance limits on free tier", "Agent can over-engineer"],
    isFeatured: true,
  },
  {
    slug: "notion-ai",
    title: "Notion AI",
    description: "AI built into your Notion workspace — drafts, summaries, translations, and Q&A across your docs.",
    category: "Productivity",
    pricing: "Paid",
    websiteUrl: "https://notion.so/product/ai",
    color: "text-zinc-100",
    bgGradient: "from-zinc-400/20 to-zinc-600/20",
    features: ["Q&A over workspace", "Auto-fill databases", "Writing assistant", "Meeting notes"],
    pros: ["Lives where your work already is", "Strong search", "Team-friendly pricing"],
    cons: ["Locked to Notion", "Generation quality varies"],
    isFeatured: true,
  },
  {
    slug: "linear",
    title: "Linear",
    description: "The issue tracker top engineering teams swear by — fast, keyboard-first, AI triage and writing built in.",
    category: "Management",
    pricing: "Freemium",
    websiteUrl: "https://linear.app",
    color: "text-indigo-300",
    bgGradient: "from-indigo-500/20 to-purple-500/20",
    features: ["Cycles & projects", "AI triage", "Roadmaps", "Slack/GitHub sync"],
    pros: ["Best-in-class UX", "Insanely fast", "Strong opinions that scale"],
    cons: ["Not great for non-engineers", "Pricier than Jira at scale"],
    isFeatured: true,
  },
  {
    slug: "vercel",
    title: "Vercel",
    description: "The platform for frontend developers — Next.js hosting, edge functions, and AI SDK for building apps.",
    category: "Other",
    pricing: "Freemium",
    websiteUrl: "https://vercel.com",
    color: "text-white",
    bgGradient: "from-zinc-700/20 to-black/20",
    features: ["Preview deployments", "Edge runtime", "AI SDK", "Analytics"],
    pros: ["Zero-config Next.js", "Generous free tier", "Top DX"],
    cons: ["Pricey at scale for heavy traffic", "Locked into their runtime"],
    isFeatured: true,
  },
  {
    slug: "framer",
    title: "Framer",
    description: "Design and ship production websites with AI — from prompt to live site without writing code.",
    category: "Design",
    pricing: "Freemium",
    websiteUrl: "https://framer.com",
    color: "text-blue-400",
    bgGradient: "from-blue-500/20 to-cyan-500/20",
    features: ["AI site generation", "CMS", "Animations", "Custom domains"],
    pros: ["Beautiful defaults", "Real CMS, not toy", "Fast publishing"],
    cons: ["Custom logic is limited", "Free tier has Framer branding"],
    isFeatured: true,
  },
  {
    slug: "elevenlabs",
    title: "ElevenLabs",
    description: "Realistic AI voice generation and cloning — used by indie creators and Hollywood alike.",
    category: "Other",
    pricing: "Freemium",
    websiteUrl: "https://elevenlabs.io",
    color: "text-zinc-200",
    bgGradient: "from-zinc-500/20 to-zinc-700/20",
    features: ["Voice cloning", "Multilingual TTS", "Voice library", "API"],
    pros: ["Most natural AI voices today", "Easy API", "Fast turnaround"],
    cons: ["Cloning ethics need care", "Credits burn fast on long content"],
    isFeatured: true,
  },
  {
    slug: "perplexity",
    title: "Perplexity",
    description: "AI answer engine with live citations — the reasoning assistant for research and curious minds.",
    category: "Assistance",
    pricing: "Freemium",
    websiteUrl: "https://perplexity.ai",
    color: "text-cyan-400",
    bgGradient: "from-cyan-500/20 to-blue-500/20",
    features: ["Live web search", "Citations", "Spaces", "Pro Search"],
    pros: ["Trustworthy with sources", "Faster than ChatGPT for facts", "Great mobile app"],
    cons: ["Pro tier needed for best models", "Sometimes over-summarizes"],
    isFeatured: true,
  },
  {
    slug: "midjourney",
    title: "Midjourney",
    description: "The image model with the most distinctive style — beloved by designers and concept artists.",
    category: "Design",
    pricing: "Paid",
    websiteUrl: "https://midjourney.com",
    color: "text-fuchsia-400",
    bgGradient: "from-fuchsia-500/20 to-pink-500/20",
    features: ["V7 model", "Style references", "Niji anime mode", "Web editor"],
    pros: ["Top-tier aesthetics", "Active community", "Consistent style refs"],
    cons: ["No free tier", "Discord-first workflow is dated"],
    isFeatured: true,
  },
  {
    slug: "runway",
    title: "Runway",
    description: "Generative video tools used in real film production — Gen-3 for text-to-video and motion brush.",
    category: "Design",
    pricing: "Freemium",
    websiteUrl: "https://runwayml.com",
    color: "text-rose-400",
    bgGradient: "from-rose-500/20 to-red-500/20",
    features: ["Text to video", "Image to video", "Motion brush", "Lip sync"],
    pros: ["Pro-grade controls", "Constantly improving", "Real creative agency"],
    cons: ["Credits burn fast", "Long renders for HQ output"],
    isFeatured: true,
  },
  {
    slug: "descript",
    title: "Descript",
    description: "Edit podcasts and videos by editing a transcript — AI cleans filler words, adds eye contact, clones voices.",
    category: "Other",
    pricing: "Freemium",
    websiteUrl: "https://descript.com",
    color: "text-yellow-400",
    bgGradient: "from-yellow-500/20 to-amber-500/20",
    features: ["Transcript-based editing", "Overdub voice cloning", "Studio Sound", "Eye contact correction"],
    pros: ["Insanely fast podcast editing", "Great for solo creators", "Studio Sound is magic"],
    cons: ["Renders can lag", "Voice cloning still uncanny on long takes"],
    isFeatured: true,
  },
  {
    slug: "lovable",
    title: "Lovable",
    description: "Full-stack AI app builder that turns plain-language descriptions into a working React + Supabase project, deployed to a live URL within minutes. Built for founders and non-developers who want a real, ejectable MVP without writing code.",
    category: "Coding",
    pricing: "Freemium",
    websiteUrl: "https://lovable.dev",
    color: "text-pink-500",
    bgGradient: "from-pink-500/20 to-rose-500/20",
    features: [
      "Natural-language full-stack generation (frontend, backend, auth, database)",
      "Live preview deployment on every change",
      "Built-in chat-driven editing of the live project",
      "Visual element selection — click into a component and describe a change",
      "Supabase Postgres + Auth + Storage wired up automatically",
      "Tailwind-styled React + Vite frontend (conventional, readable output)",
      "One-click GitHub connect and full source code export — no lock-in",
      "Integrated IDE for users who want to edit code directly",
      "Stripe and payments integration via chat command",
      "Shareable preview URLs for stakeholder review",
    ],
    pros: [
      "Fastest path from idea to deployed full-stack app for non-developers",
      "Generated code is conventional and pickup-able by a real developer",
      "True ejectability — push to your GitHub at any point and leave the tool",
      "Supabase backend means easy integration with existing data and tooling",
      "Free tier is generous enough to build a real MVP without paying",
    ],
    cons: [
      "Quality degrades once a project exceeds roughly ten screens",
      "Complex business logic still requires a developer to disentangle",
      "Message-based quotas can run out faster than expected during iteration",
      "Less control over the design system than UI-first tools like v0",
      "Cloud-only — no offline workflow",
    ],
    isFeatured: false,
  }
];
